"""v1

Revision ID: 403e1a7c1a68
Revises: 
Create Date: 2022-07-14 18:30:54.345230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '403e1a7c1a68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_shortner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('short_url', sa.String(), nullable=True),
    sa.Column('visits_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('url_visitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=True),
    sa.Column('url_id', sa.Integer(), nullable=True),
    sa.Column('where', sa.String(), nullable=False),
    sa.Column('browser_info', sa.String(length=120), nullable=False),
    sa.Column('device_ip', sa.String(length=120), nullable=False),
    sa.Column('device_visits_count', sa.Integer(), nullable=True),
    sa.Column('device_visit_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['url_shortner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_visitors')
    op.drop_table('url_shortner')
    # ### end Alembic commands ###
